# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "I'd vote for Hillary, but... | Hillary Myths"
title_postfix: " | Hillary Myths"
email: ilikehillary@example.com

description: >
  I'd vote for Hillary But... is a site designed to refute myths and
  misconceptions about Hillary Clinton. Please pick your concern from
  the following list!

sharing_image: /ivhb.png

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hillarymyths.org" # the base hostname & protocol for your site

exclude:
  - vendor
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - build.sh
  - local-serve.sh

twitter_username: hillaryclinton
github_username: devprogress

# Feedback configuration has the following structure:
# feedback:
#   action: [url to the form where the feedback is submitted]
#   input: [name of the comment input field of the feedback form]
#   url: [name url input field of the originating page]
feedback:
  action: "https://docs.google.com/forms/d/e/1FAIpQLSf7ugj0I_HBLkIhJrrAlRYf-ddQsT8awOMYFPWKG0rERrDovQ/formResponse"
  input: "entry.955832435"
  url: "entry.620619372"

# Build settings
markdown: kramdown
theme: minima

gems:
  - jekyll-sitemap

destination:  ./docs

collections:
  issues:
    output: true
    permalink: /issues/:slug/
